### ISSUE TITLE
M5公式のRFIDカードには書き込みできない？

### ISSUE THREAD

**Issue by mnltake** [ksasao/M5StackRFID2Writer#1]
M5-ATOM Lite　と　M5-RFID2 UNIT で試してみました
M5製品のおまけのカードと 
rfid Card
https://ja.aliexpress.com/item/1005004031229178.html
でやってみました書き込みはできないようです

```
PICC type: MIFARE 1KB
UID      : 3C 22 EB 9B
Writing record to NFC tag: https://m5stack.com/
                                                => Write failed.
```
 このタイプは書き込みできないんでしょうか？

お時間ありましたらよろしくお願いします

**Comment by ksasao** [comment]
動作確認ありがとうございます。こちらでは

M5Stack公式サイトのおまけカード
https://twitter.com/ksasao/status/1601831428429254656

Amazonで購入した格安RFID
https://twitter.com/ksasao/status/1602695736134889473

サンワサプライのNFCタグ
https://www.sanwa.co.jp/product/syohin?code=MM-NFCT

は書き込めています。
なお書き込みには1〜2秒かかるので、タッチ後動かさずに少し待ってみてください。

**Comment by mnltake** [comment]
おまけのカードでも書き込めるんですね
ケーブルを変えたりM5stackでやってみたりと試してますがまだ不明です
本体の不良の可能性もありそうなので　難しそうです・・・
ご回答ありがとうございました
